apiVersion: v1 
kind: PersistentVolume
metadata:
  name: my-pv-1G
spec:
  capacity:
    storage: 1Gi
accessModes:
  - ReadWriteOnce:
persistentVolumeReclaimPolicy: Delete #we can use retain or delete

